---
- name: Deploy to wrokers
  hosts: dev
  user: ansible
  connection: ssh
  gather_facts: false
  become: yes  
  tasks:

    - name: Pull Docker image from Docker Hub
      command: docker pull darshi0809/marcos

    - name: Stop and remove existing container
      command: docker rm -f darshi

    - name: Run new container
      command: docker run -d --name darshi -p 8081:8080 darshi0809/marcos
